const { BigQuery } = require('@google-cloud/bigquery');
const bigquery = new BigQuery();

/**
 * Cloud Function triggered by a Pub/Sub topic.
 * Acts as the "Event Processor" in the distributed architecture.
 */
exports.processEvent = async (message) => {
    // 1. Decode data from Pub/Sub (Handling at-least-once delivery)
    const data = JSON.parse(Buffer.from(message.data, 'base64').toString());

    const datasetId = 'analytics_db';
    const tableId = 'view_stats';

    // 2. Map the incoming event to the BigQuery table schema
    const row = {
        resourceId: data.resourceId,
        timestamp: data.timestamp,
        eventId: data.eventId, // Unique ID generated by Service A for tracking
        resourceType: data.resourceType || 'movie'
    };

    try {
        // 3. Idempotency Implementation
        // We use 'insertId' so BigQuery can automatically deduplicate events 
        // in case of Pub/Sub redeliveries
        await bigquery
            .dataset(datasetId)
            .table(tableId)
            .insert([row], { insertId: data.eventId });

        console.log(`Success: Event ${data.eventId} saved to BigQuery.`);
    } catch (error) {
        console.error('Error inserting into BigQuery:', JSON.stringify(error));
    }
};